### ISSUE TITLE
The [standard] token filter has been removed.

### ISSUE THREAD

**Issue by elastoc** [louisicard/adimeo-data-suite#10]
Bonjour,

La version  ADS 0.4.5 ne semble pas compatible avec Elasticsearch 7.10.0 sur Ubuntu 20.04.1 LTS.

Dans les logs Apache côté ADS :

[critical] Uncaught PHP Exception Elasticsearch\Common\Exceptions\BadRequest400Exception: "{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The [standard] token filter has been removed."}],"type":"illegal_argument_exception","reason":"The [standard] token filter has been removed."},"status":400}" at /blabla/adimeo-data-suite-0.4.5/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php line 630
[warning] Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (array)
[warning] Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (array)

Pourriez-vous s'il vous plait corriger ce problème ?

Cordialement,
Guillaume

**Comment by louisicard** [comment]
La nouvelle version est désormais compatible avec ES7+.
La rétrocompatibilité est assurée avec le paramètre IS_LEGACY=1
